version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64 
    tags:
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"
      - -X github.com/konstructio/kubernetes-toolkit/internal/common.Version={{.Version}}

dockers:
  - image_templates:
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }} version {{ .Version }}. See release notes at https://github.com/konstructio/{{ .ProjectName }}/releases/tag/v{{ .RawVersion }}"
      - "--label=org.opencontainers.image.url=https://github.com/konstructio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/konstructio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  
  - image_templates:
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }} version {{ .Version }}. See release notes at https://github.com/konstructio/{{ .ProjectName }}/releases/tag/v{{ .RawVersion }}"
      - "--label=org.opencontainers.image.url=https://github.com/konstructio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/konstructio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: "ghcr.io/konstructio/kubernetes-toolkit:v{{ .RawVersion }}"
    image_templates:
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-amd64"
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/konstructio/kubernetes-toolkit:v{{ .Major }}"
    image_templates:
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-amd64"
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/konstructio/kubernetes-toolkit:latest"
    image_templates:
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-amd64"
      - "ghcr.io/konstructio/kubernetes-toolkit:{{ .Tag }}-arm64"

